# platform.conf - qemu-virt-x86_64

platform = {
    arch = "x86_64",
    name = "QEMU",

    memory = {
        ram    = { base = 0x00100000, size = 0x7FF00000 },
        rootfs = { base = 0x04000000, size = 0x10000000, mb = 256 },
        reserves = {
            { name = "lowmem_1m_2m", start = 0x00100000, stop = 0x001FFFFF },
        },
    },

    mmio_vma = false,
    lapic    = true,

    uart = {
        driver    = "x86",
        base      = 0,
        reg_shift = 0,
    },

    irq = {
        driver = "none",
        gicd   = 0,
        gicc   = 0,
        gich   = 0,
        gicr   = 0,
        plic   = 0,
        clint  = 0,
    },

    timer = {
        driver     = "x86",
        tick_ms    = 10,
        freq_hz    = 100,
        cntp       = 0,
        counter_hz = 0,
    },

    eth = {
        driver = "virtio",
        base   = 0xfeb02e00,
    },
}
