/*
 * lib/platform_cfg.c — static platform runtime configuration
 *
 * Platform values are generated by tools/gen_platform.py into
 * build/<platform>/platform_static.c.  Keep the platform_get_* API stable so
 * drivers do not care whether the source is a static table or a future DTB.
 */

#include "platform_cfg.h"
#include "mm_vm.h"   /* KERNEL_VMA */
#include "string.h"

#ifndef PLATFORM_MEM_RAM_BASE
#define PLATFORM_MEM_RAM_BASE 0UL
#endif

#ifndef PLATFORM_MEM_RAM_SIZE
#define PLATFORM_MEM_RAM_SIZE 0UL
#endif

#ifndef PLATFORM_MEM_ROOTFS_BASE
#define PLATFORM_MEM_ROOTFS_BASE 0UL
#endif

#ifndef PLATFORM_MEM_ROOTFS_SIZE
#define PLATFORM_MEM_ROOTFS_SIZE 0UL
#endif

#ifndef DEVICE_MMIO_NEEDS_VMA
#define DEVICE_MMIO_NEEDS_VMA 0
#endif

uintptr_t g_mem_ram_base    = PLATFORM_MEM_RAM_BASE;
uintptr_t g_mem_ram_size    = PLATFORM_MEM_RAM_SIZE;
uintptr_t g_mem_rootfs_base = PLATFORM_MEM_ROOTFS_BASE;
uintptr_t g_mem_rootfs_size = PLATFORM_MEM_ROOTFS_SIZE;

int g_mmio_needs_vma = DEVICE_MMIO_NEEDS_VMA;

pmm_resv_t g_pmm_reserves[PMM_MAX_RESV];
int        g_pmm_resv_count = 0;

static void platform_tag_copy(char *dst, const char *src, unsigned n)
{
    unsigned i;

    for (i = 0; i < n - 1 && src && src[i]; i++)
        dst[i] = src[i];
    dst[i] = '\0';
}

uintptr_t platform_get_uintptr(const char *block, const char *key)
{
    for (unsigned i = 0; i < g_platform_static_kv_count; i++) {
        const platform_kv_t *kv = &g_platform_static_kv[i];

        if (strcmp(kv->block, block) == 0 && strcmp(kv->key, key) == 0)
            return kv->value;
    }

    return 0;
}

unsigned platform_get_uint(const char *block, const char *key)
{
    return (unsigned)platform_get_uintptr(block, key);
}

uintptr_t platform_get_mmio(const char *block, const char *key)
{
    uintptr_t addr = platform_get_uintptr(block, key);

    if (addr == 0)
        return 0;
    return g_mmio_needs_vma ? addr + KERNEL_VMA : addr;
}

void platform_conf_scan(void)
{
    g_mem_ram_base    = platform_get_uintptr("memory.ram", "base");
    g_mem_ram_size    = platform_get_uintptr("memory.ram", "size");
    g_mem_rootfs_base = platform_get_uintptr("memory.rootfs", "base");
    g_mem_rootfs_size = platform_get_uintptr("memory.rootfs", "size");
    g_mmio_needs_vma  = platform_get_uint("platform", "mmio_vma") ? 1 : 0;

    g_pmm_resv_count = 0;
    for (unsigned i = 0; i < g_platform_static_reserve_count && i < PMM_MAX_RESV; i++) {
        pmm_resv_t *dst = &g_pmm_reserves[i];
        const platform_reserve_t *src = &g_platform_static_reserves[i];

        platform_tag_copy(dst->tag, src->tag, sizeof(dst->tag));
        dst->start = src->start;
        dst->end = src->end;
        g_pmm_resv_count++;
    }
}

void platform_conf_close(void)
{
}
