# platform.conf - rk3588-aarch64

platform = {
    arch = "aarch64",
    name = "RK3588",

    memory = {
        ram    = { base = 0x00200000, size = 0xBFE00000 },
        rootfs = { base = 0x10000000, size = 0x08000000, mb = 128 },
        reserves = {
            { name = "kernel", start = 0x00200000, stop = 0x00800000 },
        },
    },

    kernel = {
        link = 0xffff000000400000,
    },

    mmio_vma = true,
    lapic    = false,

    uart = {
        driver    = "dw",
        base      = 0xFEB50000,
        reg_shift = 2,
    },

    irq = {
        driver = "gicv3",
        gicd   = 0xFE600000,
        gicc   = 0,
        gich   = 0,
        gicr   = 0xFE680000,
        plic   = 0,
        clint  = 0,
    },

    timer = {
        driver     = "aarch64",
        tick_ms    = 10,
        freq_hz    = 100,
        cntp       = 26,
        counter_hz = 0,
    },

    npu = {
        driver = "rknpu",
        base0 = 0xFDAB0000,
        base1 = 0xFDAC0000,
        base2 = 0xFDAD0000,
        pmu   = 0xFD8D8000,
        irq0  = 142,
        irq1  = 143,
        irq2  = 144,
    },
}
