[workspace]
members = [
    "kernel_support",
    "avatar_eth",
    "avatar_usb",
    "avatar_wifi",
    "third_party/aic8800",
    "third_party/sdio-host",
    "third_party/sdhci-cv1800",
    "third_party/rd-net",
    "third_party/rdif-eth",
    "third_party/rdif-base",
    "third_party/rdif-def",
    "third_party/dma-api",
    "third_party/ax-sync",
]
resolver = "2"

[workspace.package]
categories = ["embedded", "no-std"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/avatar-os/avatar-next"

[workspace.dependencies]
log = { version = "0.4", default-features = false }
tock-registers = "0.9"
atomic-waker = { version = "1", default-features = false }
axtest = { version = "0.5", default-features = false }
ax-sync = { path = "third_party/ax-sync", default-features = false }
cfg-if = "1"
derive_more = { version = "2", default-features = false, features = ["full"] }
lock_api = "0.4"
proc-macro2 = "1"
quote = "1"
syn = "=2.0.119"
thiserror = { version = "2", default-features = false }
dma-api = { path = "third_party/dma-api" }
rdif-base = { path = "third_party/rdif-base" }
rdif-def = { path = "third_party/rdif-def" }
rdif-eth = { path = "third_party/rdif-eth" }
rd-net = { path = "third_party/rd-net" }
sdio-host = { path = "third_party/sdio-host" }
sdhci-cv1800 = { path = "third_party/sdhci-cv1800" }
