[package]
name = "cvitek-usb"
version = "0.1.0"
edition = "2024"
description = "SG2002/CV1812H USB driver (DWC2 host + device), extracted from sg200x-bsp"

[dependencies]
tock-registers = "0.9"
log = { version = "0.4", default-features = false }

[features]
default = ["cv182x-host", "c906"]
cv182x-host = []
c906 = []
device-mode = []
device-cdc-acm = ["device-mode"]
usb-force-no-dma = []
