/* Auto-generated by tools/gen_device_profile.sh from config/device_profile.table */
/* Do not edit this file directly. */
#ifndef DEVICE_PROFILE_H
#define DEVICE_PROFILE_H

#include "arch.h"

#ifndef PLATFORM_QEMU
#define PLATFORM_QEMU 0
#endif

#if ARCH_AARCH64 && PLATFORM_QEMU
#define DEVICE_PROFILE_VALID          1
#define DEVICE_MMIO_NEEDS_VMA         1
#define DEVICE_DEFAULT_UART_PL011     1
#define DEVICE_DEFAULT_UART_DW        0
#define DEVICE_DEFAULT_UART_X86       0
#define DEVICE_DEFAULT_GIC_V2         1
#define DEVICE_DEFAULT_GIC_V3         0
#define DEVICE_DEFAULT_TIMER_AARCH64  1
#define DEVICE_DEFAULT_TIMER_RV       0
#define DEVICE_DEFAULT_TIMER_X86      0
#define DEVICE_UART_BASE_RAW          0x09000000UL
#define DEVICE_GICD_BASE_RAW          0x08000000UL
#define DEVICE_GICC_BASE_RAW          0x08010000UL
#define DEVICE_GICH_BASE_RAW          0x08030000UL
#define DEVICE_GICR_BASE_RAW          0x080A0000UL
#define DEVICE_PLIC_BASE_RAW          0UL
#define DEVICE_CLINT_BASE_RAW         0UL
#define DEVICE_TIMER_TICK_MS          10
#define DEVICE_TIMER_FREQUENCY_HZ     100
#define DEVICE_TIMER_COUNTER_HZ       0UL
#define DEVICE_CNTP_TIMER             30
#define DEVICE_UART_REG_SHIFT         0
#elif ARCH_RISCV64 && PLATFORM_QEMU
#define DEVICE_PROFILE_VALID          1
#define DEVICE_MMIO_NEEDS_VMA         1
#define DEVICE_DEFAULT_UART_PL011     0
#define DEVICE_DEFAULT_UART_DW        1
#define DEVICE_DEFAULT_UART_X86       0
#define DEVICE_DEFAULT_GIC_V2         0
#define DEVICE_DEFAULT_GIC_V3         0
#define DEVICE_DEFAULT_TIMER_AARCH64  0
#define DEVICE_DEFAULT_TIMER_RV       1
#define DEVICE_DEFAULT_TIMER_X86      0
#define DEVICE_UART_BASE_RAW          0x10000000UL
#define DEVICE_GICD_BASE_RAW          0UL
#define DEVICE_GICC_BASE_RAW          0UL
#define DEVICE_GICH_BASE_RAW          0UL
#define DEVICE_GICR_BASE_RAW          0UL
#define DEVICE_PLIC_BASE_RAW          0x0C000000UL
#define DEVICE_CLINT_BASE_RAW         0x02000000UL
#define DEVICE_TIMER_TICK_MS          10
#define DEVICE_TIMER_FREQUENCY_HZ     100
#define DEVICE_TIMER_COUNTER_HZ       10000000UL
#define DEVICE_CNTP_TIMER             0
#define DEVICE_UART_REG_SHIFT         0
#elif ARCH_X86_64 && PLATFORM_QEMU
#define DEVICE_PROFILE_VALID          1
#define DEVICE_MMIO_NEEDS_VMA         0
#define DEVICE_DEFAULT_UART_PL011     0
#define DEVICE_DEFAULT_UART_DW        0
#define DEVICE_DEFAULT_UART_X86       1
#define DEVICE_DEFAULT_GIC_V2         0
#define DEVICE_DEFAULT_GIC_V3         0
#define DEVICE_DEFAULT_TIMER_AARCH64  0
#define DEVICE_DEFAULT_TIMER_RV       0
#define DEVICE_DEFAULT_TIMER_X86      1
#define DEVICE_UART_BASE_RAW          0UL
#define DEVICE_GICD_BASE_RAW          0UL
#define DEVICE_GICC_BASE_RAW          0UL
#define DEVICE_GICH_BASE_RAW          0UL
#define DEVICE_GICR_BASE_RAW          0UL
#define DEVICE_PLIC_BASE_RAW          0UL
#define DEVICE_CLINT_BASE_RAW         0UL
#define DEVICE_TIMER_TICK_MS          10
#define DEVICE_TIMER_FREQUENCY_HZ     100
#define DEVICE_TIMER_COUNTER_HZ       0UL
#define DEVICE_CNTP_TIMER             0
#define DEVICE_UART_REG_SHIFT         0
#else
#error "Unsupported ARCH/PLATFORM device profile; update config/device_profile.table"
#endif

#endif /* DEVICE_PROFILE_H */
