/* Auto-generated by tools/gen_platform.py — do not edit */
#ifndef MEM_LAYOUT_H
#define MEM_LAYOUT_H

#define MEM_RAM_BASE      0x00100000UL
#define MEM_RAM_SIZE      0x7FF00000UL
#define MEM_ROOTFS_BASE   0x04000000UL
#define MEM_ROOTFS_SIZE   0x08000000UL
#define MEM_LAYOUT_VALID  1

#endif /* MEM_LAYOUT_H */
