/* Auto-generated by tools/gen_mem_layout.sh from config/mem_layout.table */
/* Do not edit this file directly. */
#ifndef MEM_LAYOUT_H
#define MEM_LAYOUT_H

#include "arch.h"

/* Platform selection macros are passed by Makefile (e.g. -DPLATFORM_QEMU=1). */
#ifndef PLATFORM_QEMU
#define PLATFORM_QEMU 0
#endif

#if ARCH_AARCH64 && PLATFORM_QEMU
#define MEM_RAM_BASE      0x40000000UL
#define MEM_RAM_SIZE      0x80000000UL
#define MEM_ROOTFS_BASE   0x60000000UL
#define MEM_ROOTFS_SIZE   0x08000000UL
#define MEM_LAYOUT_VALID  1
#elif ARCH_RISCV64 && PLATFORM_QEMU
#define MEM_RAM_BASE      0x80000000UL
#define MEM_RAM_SIZE      0x80000000UL
#define MEM_ROOTFS_BASE   0x88000000UL
#define MEM_ROOTFS_SIZE   0x08000000UL
#define MEM_LAYOUT_VALID  1
#elif ARCH_X86_64 && PLATFORM_QEMU
#define MEM_RAM_BASE      0x00100000UL
#define MEM_RAM_SIZE      0x7FF00000UL
#define MEM_ROOTFS_BASE   0x04000000UL
#define MEM_ROOTFS_SIZE   0x08000000UL
#define MEM_LAYOUT_VALID  1
#else
#error "Unsupported ARCH/PLATFORM memory layout; update config/mem_layout.table"
#endif

#endif /* MEM_LAYOUT_H */
