/* Auto-generated by tools/gen_platform.py — do not edit */
#ifndef PLATFORM_H
#define PLATFORM_H

#include "mem_layout.h"
#include "device_profile.h"
#include "pmm_reserve.h"

#endif /* PLATFORM_H */
