/* Auto-generated by tools/gen_platform.py — do not edit */
#ifndef PMM_RESERVE_H
#define PMM_RESERVE_H

#define PMM_EXTRA_RESV0_ENABLE  1
#define PMM_EXTRA_RESV0_TAG     "lowmem_1m_2m"
#define PMM_EXTRA_RESV0_START   0x0000000000100000ULL
#define PMM_EXTRA_RESV0_END     0x00000000001FFFFFULL
#define PMM_EXTRA_RESV1_ENABLE  0
#define PMM_EXTRA_RESV1_TAG     ""
#define PMM_EXTRA_RESV1_START   0ULL
#define PMM_EXTRA_RESV1_END     0ULL

#endif /* PMM_RESERVE_H */
