/* Auto-generated by tools/gen_pmm_reserve.sh from config/pmm_reserve.table */
/* Do not edit this file directly. */
#ifndef PMM_RESERVE_H
#define PMM_RESERVE_H

#include "arch.h"

#ifndef PLATFORM_QEMU
#define PLATFORM_QEMU 0
#endif

#if ARCH_AARCH64 && PLATFORM_QEMU
#define PMM_EXTRA_RESV0_ENABLE 0
#define PMM_EXTRA_RESV1_ENABLE 0
#elif ARCH_RISCV64 && PLATFORM_QEMU
#define PMM_EXTRA_RESV0_ENABLE 1
#define PMM_EXTRA_RESV0_TAG    "opensbi"
#define PMM_EXTRA_RESV0_START  0x80000000ULL
#define PMM_EXTRA_RESV0_END    0x801FFFFFULL
#define PMM_EXTRA_RESV1_ENABLE 1
#define PMM_EXTRA_RESV1_TAG    "boot_low"
#define PMM_EXTRA_RESV1_START  0x80200000ULL
#define PMM_EXTRA_RESV1_END    0x80205FFFULL
#elif ARCH_X86_64 && PLATFORM_QEMU
#define PMM_EXTRA_RESV0_ENABLE 1
#define PMM_EXTRA_RESV0_TAG    "lowmem_1m_2m"
#define PMM_EXTRA_RESV0_START  0x00100000ULL
#define PMM_EXTRA_RESV0_END    0x001FFFFFULL
#define PMM_EXTRA_RESV1_ENABLE 0
#else
#error "Unsupported ARCH/PLATFORM PMM reserve config; update config/pmm_reserve.table"
#endif

#endif /* PMM_RESERVE_H */
