#!/bin/sh
set -eu

if [ "$#" -ne 3 ]; then
    echo "usage: $0 <mem_layout.table> <out.mk> <out.h>" >&2
    exit 1
fi

src="$1"
out_mk="$2"
out_h="$3"

if [ ! -f "$src" ]; then
    echo "mem layout source not found: $src" >&2
    exit 1
fi

out_mk_dir=$(dirname "$out_mk")
out_h_dir=$(dirname "$out_h")
mkdir -p "$out_mk_dir" "$out_h_dir"

tmp_mk=$(mktemp)
tmp_h=$(mktemp)
trap 'rm -f "$tmp_mk" "$tmp_h"' EXIT

awk -v out_mk="$tmp_mk" -v out_h="$tmp_h" -v src="$src" '
function to_upper_ident(s,    i, c, out) {
    out = ""
    for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c >= "a" && c <= "z") {
            c = toupper(c)
        } else if (c == "-" || c == ".") {
            c = "_"
        }
        out = out c
    }
    return out
}

function to_int(v,    t, i, c, d, n) {
    t = v
    gsub(/[uUlL]/, "", t)
    if (substr(t, 1, 2) == "0x" || substr(t, 1, 2) == "0X") {
        n = 0
        for (i = 3; i <= length(t); i++) {
            c = substr(t, i, 1)
            if (c >= "0" && c <= "9") {
                d = c + 0
            } else if (c >= "a" && c <= "f") {
                d = 10 + index("abcdef", c) - 1
            } else if (c >= "A" && c <= "F") {
                d = 10 + index("ABCDEF", c) - 1
            } else {
                printf("invalid hex digit in value: %s\n", v) > "/dev/stderr"
                exit 1
            }
            n = n * 16 + d
        }
        return n
    }
    return t + 0
}

function to_mk_num(v,    t) {
    t = v
    gsub(/[uUlL]/, "", t)
    return t
}

BEGIN {
    line_no = 0
    arch_count = 0
    plat_count = 0
    row_count = 0
}

/^[ \t]*#/ || NF == 0 {
    next
}

{
    line_no++
    if (NF != 7) {
        printf("%s: invalid field count at logical line %d, expected 7 got %d\n", src, line_no, NF) > "/dev/stderr"
        exit 1
    }

    arch = $1
    plat = $2
    defv = $3
    ram_base = $4
    ram_size = $5
    rootfs_base = $6
    rootfs_size = $7

    key = arch "_" plat
    if (seen_key[key]++) {
        printf("%s: duplicated arch/platform entry: %s\n", src, key) > "/dev/stderr"
        exit 1
    }

    if (!(arch in seen_arch)) {
        seen_arch[arch] = 1
        arch_count++
        arch_order[arch_count] = arch
    }

    if (!(plat in seen_plat)) {
        seen_plat[plat] = 1
        plat_count++
        plat_order[plat_count] = plat
    }

    if (defv != "0" && defv != "1") {
        printf("%s: invalid default flag for %s, must be 0 or 1\n", src, key) > "/dev/stderr"
        exit 1
    }

    if (defv == "1") {
        if ((arch in default_platform) && default_platform[arch] != plat) {
            printf("%s: multiple defaults for arch %s (%s, %s)\n", src, arch, default_platform[arch], plat) > "/dev/stderr"
            exit 1
        }
        default_platform[arch] = plat
    }

    row_count++
    row_key[row_count] = key
    row_arch[row_count] = arch
    row_plat[row_count] = plat

    ram_base_map[key] = ram_base
    ram_size_map[key] = ram_size
    rootfs_base_map[key] = rootfs_base
    rootfs_size_map[key] = rootfs_size

    rootfs_mb_map[key] = int(to_int(rootfs_size) / (1024 * 1024))
    platform_define_map[key] = to_upper_ident(plat)
}

END {
    if (row_count == 0) {
        printf("%s: no entries found\n", src) > "/dev/stderr"
        exit 1
    }

    for (i = 1; i <= arch_count; i++) {
        a = arch_order[i]
        if (!(a in default_platform)) {
            printf("%s: missing default platform for arch %s\n", src, a) > "/dev/stderr"
            exit 1
        }
    }

    print "# Auto-generated by tools/gen_mem_layout.sh from " src > out_mk
    print "# Do not edit this file directly." >> out_mk
    print "" >> out_mk
    print "MEM_LAYOUT_ARCH ?= $(ARCH)" >> out_mk
    print "MEM_LAYOUT_PLATFORM ?= $(PLATFORM)" >> out_mk
    for (i = 1; i <= arch_count; i++) {
        a = arch_order[i]
        print "MEM_DEFAULT_PLATFORM_" a " := " default_platform[a] >> out_mk
    }
    print "" >> out_mk
    print "ifeq ($(strip $(MEM_LAYOUT_PLATFORM)),)" >> out_mk
    print "MEM_LAYOUT_PLATFORM := $(MEM_DEFAULT_PLATFORM_$(MEM_LAYOUT_ARCH))" >> out_mk
    print "endif" >> out_mk
    print "" >> out_mk
    print "MEM_LAYOUT_KEY := $(MEM_LAYOUT_ARCH)_$(MEM_LAYOUT_PLATFORM)" >> out_mk

    for (i = 1; i <= row_count; i++) {
        k = row_key[i]
        print "MEM_RAM_BASE_" k " := " to_mk_num(ram_base_map[k]) >> out_mk
        print "MEM_RAM_SIZE_" k " := " to_mk_num(ram_size_map[k]) >> out_mk
        print "MEM_ROOTFS_BASE_" k " := " to_mk_num(rootfs_base_map[k]) >> out_mk
        print "MEM_ROOTFS_SIZE_" k " := " to_mk_num(rootfs_size_map[k]) >> out_mk
        print "MEM_ROOTFS_SIZE_MB_" k " := " rootfs_mb_map[k] >> out_mk
        print "MEM_PLATFORM_DEFINE_" k " := " platform_define_map[k] >> out_mk
    }

    print "" >> out_mk
    print "MEM_RAM_BASE := $(MEM_RAM_BASE_$(MEM_LAYOUT_KEY))" >> out_mk
    print "MEM_RAM_SIZE := $(MEM_RAM_SIZE_$(MEM_LAYOUT_KEY))" >> out_mk
    print "MEM_ROOTFS_BASE := $(MEM_ROOTFS_BASE_$(MEM_LAYOUT_KEY))" >> out_mk
    print "MEM_ROOTFS_SIZE := $(MEM_ROOTFS_SIZE_$(MEM_LAYOUT_KEY))" >> out_mk
    print "MEM_ROOTFS_SIZE_MB := $(MEM_ROOTFS_SIZE_MB_$(MEM_LAYOUT_KEY))" >> out_mk
    print "MEM_PLATFORM_DEFINE := $(MEM_PLATFORM_DEFINE_$(MEM_LAYOUT_KEY))" >> out_mk
    print "" >> out_mk
    print "ifeq ($(strip $(MEM_RAM_BASE)),)" >> out_mk
    print "$(error Unsupported memory layout: ARCH=$(MEM_LAYOUT_ARCH) PLATFORM=$(MEM_LAYOUT_PLATFORM). Add entry to " src ")" >> out_mk
    print "endif" >> out_mk
    print "" >> out_mk
    print "ROOTFS_PHYS_ADDR := $(MEM_ROOTFS_BASE)" >> out_mk
    print "ROOTFS_SIZE_MB := $(MEM_ROOTFS_SIZE_MB)" >> out_mk

    print "/* Auto-generated by tools/gen_mem_layout.sh from " src " */" > out_h
    print "/* Do not edit this file directly. */" >> out_h
    print "#ifndef MEM_LAYOUT_H" >> out_h
    print "#define MEM_LAYOUT_H" >> out_h
    print "" >> out_h
    print "#include \"arch.h\"" >> out_h
    print "" >> out_h
    print "/* Platform selection macros are passed by Makefile (e.g. -DPLATFORM_QEMU=1). */" >> out_h
    for (i = 1; i <= plat_count; i++) {
        p = plat_order[i]
        pu = to_upper_ident(p)
        print "#ifndef PLATFORM_" pu >> out_h
        print "#define PLATFORM_" pu " 0" >> out_h
        print "#endif" >> out_h
    }
    print "" >> out_h

    for (i = 1; i <= row_count; i++) {
        a = row_arch[i]
        p = row_plat[i]
        au = to_upper_ident(a)
        pu = to_upper_ident(p)

        if (i == 1) {
            print "#if ARCH_" au " && PLATFORM_" pu >> out_h
        } else {
            print "#elif ARCH_" au " && PLATFORM_" pu >> out_h
        }

        k = row_key[i]
        print "#define MEM_RAM_BASE      " ram_base_map[k] >> out_h
        print "#define MEM_RAM_SIZE      " ram_size_map[k] >> out_h
        print "#define MEM_ROOTFS_BASE   " rootfs_base_map[k] >> out_h
        print "#define MEM_ROOTFS_SIZE   " rootfs_size_map[k] >> out_h
        print "#define MEM_LAYOUT_VALID  1" >> out_h
    }

    print "#else" >> out_h
    print "#error \"Unsupported ARCH/PLATFORM memory layout; update config/mem_layout.table\"" >> out_h
    print "#endif" >> out_h
    print "" >> out_h
    print "#endif /* MEM_LAYOUT_H */" >> out_h
}
' "$src"

if [ ! -f "$out_mk" ] || ! cmp -s "$tmp_mk" "$out_mk"; then
    mv "$tmp_mk" "$out_mk"
else
    rm -f "$tmp_mk"
fi

if [ ! -f "$out_h" ] || ! cmp -s "$tmp_h" "$out_h"; then
    mv "$tmp_h" "$out_h"
else
    rm -f "$tmp_h"
fi
