#!/bin/sh
set -eu

if [ "$#" -ne 3 ]; then
    echo "usage: $0 <device_profile.table> <out.mk> <out.h>" >&2
    exit 1
fi

src="$1"
out_mk="$2"
out_h="$3"

if [ ! -f "$src" ]; then
    echo "device profile source not found: $src" >&2
    exit 1
fi

mkdir -p "$(dirname "$out_mk")" "$(dirname "$out_h")"

tmp_mk=$(mktemp)
tmp_h=$(mktemp)
trap 'rm -f "$tmp_mk" "$tmp_h"' EXIT

awk -v out_mk="$tmp_mk" -v out_h="$tmp_h" -v src="$src" '
function to_upper_ident(s,    i, c, out) {
    out = ""
    for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c >= "a" && c <= "z") {
            c = toupper(c)
        } else if (c == "-" || c == ".") {
            c = "_"
        }
        out = out c
    }
    return out
}

function uart_src(u) {
    if (u == "pl011") return "driver/uart/uart_pl011.c"
    if (u == "dw") return "driver/uart/uart_dw.c"
    if (u == "x86") return "driver/uart/uart_x86.c"
    printf("%s: unsupported uart value: %s\n", src, u) > "/dev/stderr"
    exit 1
}

function gic_src(g) {
    if (g == "v2") return "driver/irq/gicv2.c"
    if (g == "v3") return "driver/irq/gicv3.c"
    if (g == "none") return ""
    printf("%s: unsupported gic value: %s\n", src, g) > "/dev/stderr"
    exit 1
}

function timer_src(t) {
    if (t == "aarch64" || t == "rv" || t == "x86") return "driver/timer/timer.c"
    printf("%s: unsupported timer value: %s\n", src, t) > "/dev/stderr"
    exit 1
}

BEGIN {
    arch_count = 0
    plat_count = 0
    row_count = 0
}

/^[ \t]*#/ || NF == 0 { next }

{
    if (NF != 20) {
        printf("%s: invalid field count, expected 20 got %d\n", src, NF) > "/dev/stderr"
        exit 1
    }

    arch=$1; plat=$2; defv=$3
    uart=$4; gic=$5; timer=$6
    mmio_vma=$7
    uart_base=$8; gicd=$9; gicc=$10; gich=$11; gicr=$12; plic=$13; clint=$14
    tick_ms=$15; tick_hz=$16; counter_hz=$17; cntp_timer=$18; uart_reg_shift=$19; need_lapic=$20

    key = arch "_" plat
    if (seen_key[key]++) {
        printf("%s: duplicated arch/platform entry: %s\n", src, key) > "/dev/stderr"
        exit 1
    }

    if (!(arch in seen_arch)) {
        seen_arch[arch] = 1
        arch_count++
        arch_order[arch_count] = arch
    }

    if (!(plat in seen_plat)) {
        seen_plat[plat] = 1
        plat_count++
        plat_order[plat_count] = plat
    }

    if (defv != "0" && defv != "1") {
        printf("%s: default must be 0 or 1 for %s\n", src, key) > "/dev/stderr"
        exit 1
    }

    if (defv == "1") {
        if ((arch in default_platform) && default_platform[arch] != plat) {
            printf("%s: multiple defaults for arch %s\n", src, arch) > "/dev/stderr"
            exit 1
        }
        default_platform[arch] = plat
    }

    if (mmio_vma != "0" && mmio_vma != "1") {
        printf("%s: mmio_vma must be 0/1 for %s\n", src, key) > "/dev/stderr"
        exit 1
    }
    if (need_lapic != "0" && need_lapic != "1") {
        printf("%s: need_lapic must be 0/1 for %s\n", src, key) > "/dev/stderr"
        exit 1
    }

    row_count++
    row_key[row_count] = key
    row_arch[row_count] = arch
    row_plat[row_count] = plat

    uart_map[key] = uart
    gic_map[key] = gic
    timer_map[key] = timer
    mmio_vma_map[key] = mmio_vma
    uart_base_map[key] = uart_base
    gicd_map[key] = gicd
    gicc_map[key] = gicc
    gich_map[key] = gich
    gicr_map[key] = gicr
    plic_map[key] = plic
    clint_map[key] = clint
    tick_ms_map[key] = tick_ms
    tick_hz_map[key] = tick_hz
    counter_hz_map[key] = counter_hz
    cntp_timer_map[key] = cntp_timer
    uart_reg_shift_map[key] = uart_reg_shift
    need_lapic_map[key] = need_lapic

    uart_src_map[key] = uart_src(uart)
    gic_src_map[key] = gic_src(gic)
    timer_src_map[key] = timer_src(timer)
}

END {
    if (row_count == 0) {
        printf("%s: no entries found\n", src) > "/dev/stderr"
        exit 1
    }
    for (i = 1; i <= arch_count; i++) {
        a = arch_order[i]
        if (!(a in default_platform)) {
            printf("%s: missing default platform for arch %s\n", src, a) > "/dev/stderr"
            exit 1
        }
    }

    print "# Auto-generated by tools/gen_device_profile.sh from " src > out_mk
    print "# Do not edit this file directly." >> out_mk
    print "" >> out_mk
    print "DEVICE_PROFILE_ARCH ?= $(ARCH)" >> out_mk
    print "DEVICE_PROFILE_PLATFORM ?= $(PLATFORM)" >> out_mk
    for (i = 1; i <= arch_count; i++) {
        a = arch_order[i]
        print "DEVICE_DEFAULT_PLATFORM_" a " := " default_platform[a] >> out_mk
    }
    print "" >> out_mk
    print "ifeq ($(strip $(DEVICE_PROFILE_PLATFORM)),)" >> out_mk
    print "DEVICE_PROFILE_PLATFORM := $(DEVICE_DEFAULT_PLATFORM_$(DEVICE_PROFILE_ARCH))" >> out_mk
    print "endif" >> out_mk
    print "DEVICE_PROFILE_KEY := $(DEVICE_PROFILE_ARCH)_$(DEVICE_PROFILE_PLATFORM)" >> out_mk

    for (i = 1; i <= row_count; i++) {
        k = row_key[i]
        print "DEV_DEFAULT_UART_" k " := " uart_map[k] >> out_mk
        print "DEV_DEFAULT_GIC_" k " := " gic_map[k] >> out_mk
        print "DEV_DEFAULT_TIMER_" k " := " timer_map[k] >> out_mk
        print "DEV_UART_SRC_" k " := " uart_src_map[k] >> out_mk
        print "DEV_IRQ_SRC_" k " := " gic_src_map[k] >> out_mk
        print "DEV_TIMER_SRC_" k " := " timer_src_map[k] >> out_mk
        print "DEV_NEED_LAPIC_" k " := " need_lapic_map[k] >> out_mk
    }

    print "" >> out_mk
    print "DEV_DEFAULT_UART := $(DEV_DEFAULT_UART_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "DEV_DEFAULT_GIC := $(DEV_DEFAULT_GIC_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "DEV_DEFAULT_TIMER := $(DEV_DEFAULT_TIMER_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "DEV_UART_SRC := $(DEV_UART_SRC_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "DEV_IRQ_SRC := $(DEV_IRQ_SRC_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "DEV_TIMER_SRC := $(DEV_TIMER_SRC_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "DEV_NEED_LAPIC := $(DEV_NEED_LAPIC_$(DEVICE_PROFILE_KEY))" >> out_mk
    print "" >> out_mk
    print "ifeq ($(strip $(DEV_UART_SRC)),)" >> out_mk
    print "$(error Unsupported device profile: ARCH=$(DEVICE_PROFILE_ARCH) PLATFORM=$(DEVICE_PROFILE_PLATFORM). Add entry to " src ")" >> out_mk
    print "endif" >> out_mk

    print "/* Auto-generated by tools/gen_device_profile.sh from " src " */" > out_h
    print "/* Do not edit this file directly. */" >> out_h
    print "#ifndef DEVICE_PROFILE_H" >> out_h
    print "#define DEVICE_PROFILE_H" >> out_h
    print "" >> out_h
    print "#include \"arch.h\"" >> out_h
    print "" >> out_h

    for (i = 1; i <= plat_count; i++) {
        p = plat_order[i]
        pu = to_upper_ident(p)
        print "#ifndef PLATFORM_" pu >> out_h
        print "#define PLATFORM_" pu " 0" >> out_h
        print "#endif" >> out_h
    }
    print "" >> out_h

    for (i = 1; i <= row_count; i++) {
        a = to_upper_ident(row_arch[i])
        p = to_upper_ident(row_plat[i])
        k = row_key[i]

        if (i == 1) {
            print "#if ARCH_" a " && PLATFORM_" p >> out_h
        } else {
            print "#elif ARCH_" a " && PLATFORM_" p >> out_h
        }

        print "#define DEVICE_PROFILE_VALID          1" >> out_h
        print "#define DEVICE_MMIO_NEEDS_VMA         " mmio_vma_map[k] >> out_h

        print "#define DEVICE_DEFAULT_UART_PL011     " (uart_map[k] == "pl011" ? 1 : 0) >> out_h
        print "#define DEVICE_DEFAULT_UART_DW        " (uart_map[k] == "dw" ? 1 : 0) >> out_h
        print "#define DEVICE_DEFAULT_UART_X86       " (uart_map[k] == "x86" ? 1 : 0) >> out_h

        print "#define DEVICE_DEFAULT_GIC_V2         " (gic_map[k] == "v2" ? 1 : 0) >> out_h
        print "#define DEVICE_DEFAULT_GIC_V3         " (gic_map[k] == "v3" ? 1 : 0) >> out_h

        print "#define DEVICE_DEFAULT_TIMER_AARCH64  " (timer_map[k] == "aarch64" ? 1 : 0) >> out_h
        print "#define DEVICE_DEFAULT_TIMER_RV       " (timer_map[k] == "rv" ? 1 : 0) >> out_h
        print "#define DEVICE_DEFAULT_TIMER_X86      " (timer_map[k] == "x86" ? 1 : 0) >> out_h

        print "#define DEVICE_UART_BASE_RAW          " uart_base_map[k] >> out_h
        print "#define DEVICE_GICD_BASE_RAW          " gicd_map[k] >> out_h
        print "#define DEVICE_GICC_BASE_RAW          " gicc_map[k] >> out_h
        print "#define DEVICE_GICH_BASE_RAW          " gich_map[k] >> out_h
        print "#define DEVICE_GICR_BASE_RAW          " gicr_map[k] >> out_h
        print "#define DEVICE_PLIC_BASE_RAW          " plic_map[k] >> out_h
        print "#define DEVICE_CLINT_BASE_RAW         " clint_map[k] >> out_h

        print "#define DEVICE_TIMER_TICK_MS          " tick_ms_map[k] >> out_h
        print "#define DEVICE_TIMER_FREQUENCY_HZ     " tick_hz_map[k] >> out_h
        print "#define DEVICE_TIMER_COUNTER_HZ       " counter_hz_map[k] >> out_h
        print "#define DEVICE_CNTP_TIMER             " cntp_timer_map[k] >> out_h
        print "#define DEVICE_UART_REG_SHIFT         " uart_reg_shift_map[k] >> out_h
    }

    print "#else" >> out_h
    print "#error \"Unsupported ARCH/PLATFORM device profile; update config/device_profile.table\"" >> out_h
    print "#endif" >> out_h
    print "" >> out_h
    print "#endif /* DEVICE_PROFILE_H */" >> out_h
}
' "$src"

if [ ! -f "$out_mk" ] || ! cmp -s "$tmp_mk" "$out_mk"; then
    mv "$tmp_mk" "$out_mk"
else
    rm -f "$tmp_mk"
fi

if [ ! -f "$out_h" ] || ! cmp -s "$tmp_h" "$out_h"; then
    mv "$tmp_h" "$out_h"
else
    rm -f "$tmp_h"
fi
