#!/bin/sh
set -eu

if [ "$#" -ne 2 ]; then
    echo "usage: $0 <pmm_reserve.table> <out.h>" >&2
    exit 1
fi

src="$1"
out_h="$2"

if [ ! -f "$src" ]; then
    echo "pmm reserve source not found: $src" >&2
    exit 1
fi

out_h_dir=$(dirname "$out_h")
mkdir -p "$out_h_dir"

tmp_h=$(mktemp)
trap 'rm -f "$tmp_h"' EXIT

awk -v out_h="$tmp_h" -v src="$src" '
function to_upper_ident(s,    i, c, out) {
    out = ""
    for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c >= "a" && c <= "z") {
            c = toupper(c)
        } else if (c == "-" || c == ".") {
            c = "_"
        }
        out = out c
    }
    return out
}

BEGIN {
    row_count = 0
    plat_count = 0
}

/^[ \t]*#/ || NF == 0 {
    next
}

{
    if (NF != 8) {
        printf("%s: invalid field count, expected 8 got %d\n", src, NF) > "/dev/stderr"
        exit 1
    }

    arch = $1
    plat = $2

    key = arch "_" plat
    if (seen_key[key]++) {
        printf("%s: duplicated arch/platform entry: %s\n", src, key) > "/dev/stderr"
        exit 1
    }

    row_count++
    row_arch[row_count] = arch
    row_plat[row_count] = plat

    r0_tag[row_count] = $3
    r0_start[row_count] = $4
    r0_end[row_count] = $5

    r1_tag[row_count] = $6
    r1_start[row_count] = $7
    r1_end[row_count] = $8

    if (!(plat in seen_plat)) {
        seen_plat[plat] = 1
        plat_count++
        plat_order[plat_count] = plat
    }
}

END {
    if (row_count == 0) {
        printf("%s: no entries found\n", src) > "/dev/stderr"
        exit 1
    }

    print "/* Auto-generated by tools/gen_pmm_reserve.sh from " src " */" > out_h
    print "/* Do not edit this file directly. */" >> out_h
    print "#ifndef PMM_RESERVE_H" >> out_h
    print "#define PMM_RESERVE_H" >> out_h
    print "" >> out_h
    print "#include \"arch.h\"" >> out_h
    print "" >> out_h

    for (i = 1; i <= plat_count; i++) {
        pu = to_upper_ident(plat_order[i])
        print "#ifndef PLATFORM_" pu >> out_h
        print "#define PLATFORM_" pu " 0" >> out_h
        print "#endif" >> out_h
    }

    print "" >> out_h

    for (i = 1; i <= row_count; i++) {
        au = to_upper_ident(row_arch[i])
        pu = to_upper_ident(row_plat[i])

        if (i == 1) {
            print "#if ARCH_" au " && PLATFORM_" pu >> out_h
        } else {
            print "#elif ARCH_" au " && PLATFORM_" pu >> out_h
        }

        if (r0_tag[i] != "none") {
            print "#define PMM_EXTRA_RESV0_ENABLE 1" >> out_h
            print "#define PMM_EXTRA_RESV0_TAG    \"" r0_tag[i] "\"" >> out_h
            print "#define PMM_EXTRA_RESV0_START  " r0_start[i] >> out_h
            print "#define PMM_EXTRA_RESV0_END    " r0_end[i] >> out_h
        } else {
            print "#define PMM_EXTRA_RESV0_ENABLE 0" >> out_h
        }

        if (r1_tag[i] != "none") {
            print "#define PMM_EXTRA_RESV1_ENABLE 1" >> out_h
            print "#define PMM_EXTRA_RESV1_TAG    \"" r1_tag[i] "\"" >> out_h
            print "#define PMM_EXTRA_RESV1_START  " r1_start[i] >> out_h
            print "#define PMM_EXTRA_RESV1_END    " r1_end[i] >> out_h
        } else {
            print "#define PMM_EXTRA_RESV1_ENABLE 0" >> out_h
        }
    }

    print "#else" >> out_h
    print "#error \"Unsupported ARCH/PLATFORM PMM reserve config; update config/pmm_reserve.table\"" >> out_h
    print "#endif" >> out_h
    print "" >> out_h
    print "#endif /* PMM_RESERVE_H */" >> out_h
}
' "$src"

if [ ! -f "$out_h" ] || ! cmp -s "$tmp_h" "$out_h"; then
    mv "$tmp_h" "$out_h"
else
    rm -f "$tmp_h"
fi
